// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/que.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_SUCCESS            Status = 1
	Status_FAILURE            Status = 2
	Status_NOT_FOUND          Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAILURE",
		3: "NOT_FOUND",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUCCESS":            1,
		"FAILURE":            2,
		"NOT_FOUND":          3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_que_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_proto_que_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_que_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_pkg_proto_que_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_que_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_que_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=pypeline.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_pkg_proto_que_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_que_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_que_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type GetQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Querykey      string                 `protobuf:"bytes,1,opt,name=querykey,proto3" json:"querykey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryRequest) Reset() {
	*x = GetQueryRequest{}
	mi := &file_pkg_proto_que_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryRequest) ProtoMessage() {}

func (x *GetQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_que_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryRequest.ProtoReflect.Descriptor instead.
func (*GetQueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_que_proto_rawDescGZIP(), []int{2}
}

func (x *GetQueryRequest) GetQuerykey() string {
	if x != nil {
		return x.Querykey
	}
	return ""
}

type GetQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=pypeline.Status" json:"status,omitempty"`
	Queryresult   *structpb.Struct       `protobuf:"bytes,2,opt,name=queryresult,proto3" json:"queryresult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryResponse) Reset() {
	*x = GetQueryResponse{}
	mi := &file_pkg_proto_que_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryResponse) ProtoMessage() {}

func (x *GetQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_que_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryResponse.ProtoReflect.Descriptor instead.
func (*GetQueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_que_proto_rawDescGZIP(), []int{3}
}

func (x *GetQueryResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *GetQueryResponse) GetQueryresult() *structpb.Struct {
	if x != nil {
		return x.Queryresult
	}
	return nil
}

var File_pkg_proto_que_proto protoreflect.FileDescriptor

const file_pkg_proto_que_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/que.proto\x12\bpypeline\x1a\x1cgoogle/protobuf/struct.proto\"]\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x127\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"9\n" +
	"\rQueryResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.pypeline.StatusR\x06status\"-\n" +
	"\x0fGetQueryRequest\x12\x1a\n" +
	"\bquerykey\x18\x01 \x01(\tR\bquerykey\"w\n" +
	"\x10GetQueryResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.pypeline.StatusR\x06status\x129\n" +
	"\vqueryresult\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vqueryresult*I\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x032\x92\x01\n" +
	"\fQueryService\x12?\n" +
	"\fExecuteQuery\x12\x16.pypeline.QueryRequest\x1a\x17.pypeline.QueryResponse\x12A\n" +
	"\bGetQuery\x12\x19.pypeline.GetQueryRequest\x1a\x1a.pypeline.GetQueryResponseB,Z*github.com/suman9054/zeone/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_que_proto_rawDescOnce sync.Once
	file_pkg_proto_que_proto_rawDescData []byte
)

func file_pkg_proto_que_proto_rawDescGZIP() []byte {
	file_pkg_proto_que_proto_rawDescOnce.Do(func() {
		file_pkg_proto_que_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_que_proto_rawDesc), len(file_pkg_proto_que_proto_rawDesc)))
	})
	return file_pkg_proto_que_proto_rawDescData
}

var file_pkg_proto_que_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_que_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_que_proto_goTypes = []any{
	(Status)(0),              // 0: pypeline.Status
	(*QueryRequest)(nil),     // 1: pypeline.QueryRequest
	(*QueryResponse)(nil),    // 2: pypeline.QueryResponse
	(*GetQueryRequest)(nil),  // 3: pypeline.GetQueryRequest
	(*GetQueryResponse)(nil), // 4: pypeline.GetQueryResponse
	(*structpb.Struct)(nil),  // 5: google.protobuf.Struct
}
var file_pkg_proto_que_proto_depIdxs = []int32{
	5, // 0: pypeline.QueryRequest.parameters:type_name -> google.protobuf.Struct
	0, // 1: pypeline.QueryResponse.status:type_name -> pypeline.Status
	0, // 2: pypeline.GetQueryResponse.status:type_name -> pypeline.Status
	5, // 3: pypeline.GetQueryResponse.queryresult:type_name -> google.protobuf.Struct
	1, // 4: pypeline.QueryService.ExecuteQuery:input_type -> pypeline.QueryRequest
	3, // 5: pypeline.QueryService.GetQuery:input_type -> pypeline.GetQueryRequest
	2, // 6: pypeline.QueryService.ExecuteQuery:output_type -> pypeline.QueryResponse
	4, // 7: pypeline.QueryService.GetQuery:output_type -> pypeline.GetQueryResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_que_proto_init() }
func file_pkg_proto_que_proto_init() {
	if File_pkg_proto_que_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_que_proto_rawDesc), len(file_pkg_proto_que_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_que_proto_goTypes,
		DependencyIndexes: file_pkg_proto_que_proto_depIdxs,
		EnumInfos:         file_pkg_proto_que_proto_enumTypes,
		MessageInfos:      file_pkg_proto_que_proto_msgTypes,
	}.Build()
	File_pkg_proto_que_proto = out.File
	file_pkg_proto_que_proto_goTypes = nil
	file_pkg_proto_que_proto_depIdxs = nil
}
